### PR TITLE
`espwlmon` - Python GUI front end

### PR DESCRIPTION
**Pull request by omnitex**
Bare bones version: [PySimpleGUI](https://www.pysimplegui.org/en/latest/) + [plotting a 2d heatmap](https://stackoverflow.com/questions/33282368/plotting-a-2d-heatmap) for erase counts.

The erase counts will ideally be made into hoverable/clickable elements.

- [x] now realized the text is not copyable and it looks like PySimpleGUI does not allow simple solution...
- [x] 'refactoring' broke Plotly export as it needs variables that are now moved to functions
- [x] error json
- [x] readme
- [x] overall EC from records + from move, cycle, pos
- [x] everything except address in base 10?
- [x] add info on failed json parse to 'make sure wlmon is flashed'

### CODE REVIEW

**Comment by omnitex** [comment]
https://plotly.com/python/2D-Histogram/ this looks perfect, the `Displaying Text` example. but the created figure is `plotly.graph_object.Figure` which lacks `set_canvas()` which is called by `FigureCanvasTkAgg()`, so it fails on

```
AttributeError: 'Figure' object has no attribute 'set_canvas'
```
in `matplotlib/backend_bases.py:1682`

**Comment by omnitex** [comment]
Concerning Plotly, I've read there's now way to tie it with Tkiner, as it is web based. So settled for non hoverable matplotlib heatmap in gui and an option to export Plotly html.

**Comment by omnitex** [comment]
- [ ] yeah so for bigger partitions (more sectors) the heatmap does not really scale at all + for heatmap dimensions where X != Y it crashes as I incorrectly mark invalid sectors only with the X coord

**Comment by pacucha42** [comment]
I'm not Python expert - however LGTM!

**Comment by omnitex** [comment]
will merge even though it's not ideal in some aspects but works well enough

**Pull request merged**
